# Generated by Django 3.2.6 on 2021-08-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='exam',
        ),
    ]
