# Generated by Django 3.2.7 on 2021-12-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_exma_result_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='required_score_pass',
            field=models.IntegerField(default=40),
        ),
    ]
