# Generated by Django 3.2.7 on 2021-12-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_exam_required_score_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='number_of_questions',
        ),
    ]
