# Generated by Django 3.2.7 on 2021-12-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_exam_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='required_score_pass',
            field=models.IntegerField(default=20),
        ),
    ]
