# Generated by Django 3.2.7 on 2021-12-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_exam_required_score_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='number_of_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='required_score_pass',
            field=models.IntegerField(default=40),
        ),
    ]
