# Generated by Django 3.2.6 on 2022-03-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
    ]
