# Generated by Django 3.2.6 on 2021-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
