# Generated by Django 3.2.6 on 2021-08-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_syllabus_is_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Syllabus',
            new_name='Curriculum',
        ),
    ]
