# Generated by Django 4.0 on 2021-12-29 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_rename_syllabus_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='classroom.subject'),
        ),
    ]
