# Generated by Django 4.0 on 2022-04-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_curriculum_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
