# Generated by Django 4.0.4 on 2022-04-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.TextField(default='None'),
        ),
    ]
