# Generated by Django 4.0.4 on 2022-04-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='points',
        ),
    ]
