# Generated by Django 4.0.4 on 2022-04-27 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_remove_assignment_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
