# Generated by Django 4.0.4 on 2022-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.TextField(default='answer'),
        ),
    ]
