# Generated by Django 4.0.4 on 2022-04-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_submission_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='answer',
            new_name='content',
        ),
    ]
